# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy Cash exchanger backend APIs 
        # uses: appleboy/ssh-action@master
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker Container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
            # host: ${{secrets.SSH_HOST}} #IP address of server to SSH into
            # username: ${{secrets.SSH_USERNAME}}
            # key: ${{secrets.SSH_KEY}} # Private or public key of the server
            email: ${{ env.HEROKU_EMAIL }} # your heroku email
            api_key: ${{ env.HEROKU_API_KEY }} # your heroku api key
            app_name: ${{ env.HEROKU_APP_NAME }} # you aplication name
            dockerfile_path: '.' # set the path to the folder where the Dockerfile is located
            process_type: 'web' # Specify the process type you want to build and release
            secrets: |
              "PORT"=${{env.PORT}}
              "OTHERS"=${{env.OTHERS}}
